mod 'puppet/nginx', '3.3.0'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppet/r10k'
mod 'herculesteam-augeasproviders_grub'
mod 'herculesteam/augeasproviders_core'
mod 'puppet/systemd'
mod 'puppetlabs/inifile'
mod 'puppetlabs-vcsrepo', '5.0.0'
mod 'choria-mcollective', '0.13.4'